apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devops-assignment
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_DATABASE: Zmxhc2tkYg==
  MYSQL_USER: Zmxhc2t1c2Vy
  MYSQL_PASSWORD: Zmxhc2twYXNz
